
version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=wallet
      - DATABASE_PASSWORD=T3ST3
      - DATABASE_NAME=wallet-test
      - PORT=5000
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=wallet
      - POSTGRES_PASSWORD=T3ST3
      - POSTGRES_DB=wallet-test
    ports:
      - "5432:5432"
    volumes:
      - "./resources/schema.sql:/docker-entrypoint-initdb.d/init.sql"
      - "wallet_pg_data:/var/lib/postgresql/data"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "foo@bar.com"
      PGADMIN_DEFAULT_PASSWORD: "bar"
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/root/.pgadmin
    restart: unless-stopped

volumes:
  wallet_pg_data:
  pgadmin: